function [] = goBioMechPro()
%% Main UI
% Call >> goBioMechPro 
% to get started.
% 
% INPUT)
% -
% OUTPUT)
% -
% NOTES)
% The UI might not function properly in R2014a and earlier.
% It is also unlikely to fully work on Macs (e.g. pathnames / vs \)
% The UI was made on a 1920x1080 monitor, but resizing is possible.

% Mark Vlutters - University of Twente - Dec 2015

clear variables; close all; clc;

%% Get computer screen info

scrsiz = get(0,'screensize');

%% Create main figure

h1338 = figure;

% 'handlevisibility','off',...
% 'closerequestfcn',{@gBMP_mainclosewarn,h1338},...
set(h1338,...
    'color',[0.95 0.95 0.95],...
    'dockcontrols','off',...
    'integerhandle','off',...
    'inverthardcopy','off',...
    'menubar','none',...
    'name','goBioMechPro',...
    'position',[ scrsiz(3)./2 0.05*scrsiz(4) 0.9.*scrsiz(3)./2 0.875*scrsiz(4)],...
    'tag','h1338',...
    'toolbar','none',...
    'userdata',''); % Used for active settings file name

%% Create UI menubar

% == Menus ==
% File
hfile = uimenu(h1338,...
    'label','File',...
    'tag','uifile');

uimenu(hfile,...
    'label','New',...
    'callback','goBioMechPro',...
    'accelerator','n',...
    'tag','uinew');

uimenu(hfile,...
    'label','Open...',...
    'callback',{@gBMP_mainopen,h1338},...
    'accelerator','o',...
    'tag','uiopen');

uimenu(hfile,...
    'label','Open module...',...
    'callback',{@gBMP_modopen,h1338},...
    'accelerator','m',...
    'tag','uiopenmod');

uimenu(hfile,...
    'label','Close module',...
    'callback',{@gBMP_modclose,h1338},...
    'accelerator','w',...
    'tag','uiclosemod',...
    'separator','on');

uimenu(hfile,...
    'label','Close all modules',...
    'callback',{@gBMP_modcloseall,h1338},...
    'tag','uiallclosemod');

uimenu(hfile,...
    'label','Save',...
    'callback',{@gBMP_mainsave,h1338},...
    'accelerator','s',...
    'tag','uisave');

uimenu(hfile,...
    'label','Save as...',...
    'callback',{@gBMP_mainsaveas,h1338},...
    'tag','uisaveas');

uimenu(hfile,...
    'label','Subject to file...',...
    'callback',{@gBMP_subj2file,h1338},...
    'tag','uis2f');

% Processing
hproc = uimenu(h1338,...
    'label','Processing',...
    'tag','uiproc');

uimenu(hproc,...
    'callback',{@gBMP_unigall,h1338},...
    'label','(Un)ignore all',...
    'tag','uiunia');

uimenu(hproc,...
    'callback',{@gBMP_modSort,h1338},...
    'label','Sort module tabs',...
    'tag','uisortmod');

uimenu(hproc,...
    'checked','off',...
    'callback',{@gBMP_keeplegacy},...
    'label','Keep legacy files',...
    'tag','uikeeplegacy');

% Help
hhelp = uimenu(h1338,...
    'label','Help',...
    'tag','uihelp');

uimenu(hhelp,...
    'label','About',...
    'callback',@gBMP_about,...
    'tag','uiabout');

uimenu(hhelp,...
    'label','Module info',...
    'callback',{@gBMP_modhelp,h1338},...
    'accelerator','h',...
    'tag','uimodinfo');

%% Create UI Toolbar

% Main toolbar
htoolbar = uitoolbar(h1338);

% Run button
img(:,:,1) = zeros(17); % R
img(:,:,2) = ones(17)*0.9; % G
img(:,:,3) = zeros(17); % B
uipushtool(htoolbar,...
    'CData',img,...
    'clickedcallback',{@gBMP_modrun,h1338},...
    'tag','psh>',...
    'enable','off');

% Remove exception button
img(:,:,1) = ones(17)*0.9 - ((eye(17)+fliplr(eye(17)))>0)*0.9;
img(:,:,2) = ones(17)*0.4 - ((eye(17)+fliplr(eye(17)))>0)*0.4;
img(:,:,3) = zeros(17);
uipushtool(htoolbar,...
    'CData',img,...
    'clickedcallback',{@gBMP_modremxcpt,h1338},...
    'tag','psh&-',...
    'enable','off');

% Add exception button
img(:,:,1) = ones(17)*0.9;
img(:,:,2) = ones(17)*0.4;
img(:,:,3) = zeros(17);
img(:,9,:) = 0; img(9,:,:) = 0;
uipushtool(htoolbar,...
    'CData',img,...
    'clickedcallback',{@gBMP_modaddxcpt,h1338},...
    'tag','psh&+',...
    'enable','off');

%% Create progress bar
% Using empty text fields

% Subject progress bar
uicontrol(h1338,...
    'backgroundcolor',[0 0.9 0],...
    'string','',...
    'style','text',...
    'tag','txtProgBarS',...
    'units','normalized',... % Be sure to set units before position
    'position',[0 0.975 0 0.025]);

% Trial progress bar
uicontrol(h1338,...
    'backgroundcolor',[0 0.9 0],...
    'string','',...
    'style','text',...
    'tag','txtProgBarT',...
    'units','normalized',... % Be sure to set units before position
    'position',[0 0.95 0 0.025]);

% Text on top of subject progress bar
uicontrol(h1338,...
    'backgroundcolor',[0.95 0.95 0.95],...
    'horizontalalignment','center',...
    'fontweight','bold',...
    'string','Current subject: 0',...
    'style','text',...
    'tag','txtSubjProg',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.425 0.9825 0.15 0.0125]);

% Text on top of trial progress bar
uicontrol(h1338,...
    'backgroundcolor',[0.95 0.95 0.95],...
    'horizontalalignment','center',...
    'fontweight','bold',...
    'string','Current trial: 0',...
    'style','text',...
    'tag','txtTrialProg',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.425 0.9575 0.15 0.0125]);

% Separator 1
uicontrol(h1338,...
    'backgroundcolor',[0 0 0],...
    'string','',...
    'style','text',...
    'tag','txtBarSep1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0 0.9745 1 0.0005]);

% Separator 2
uicontrol(h1338,...
    'backgroundcolor',[0 0 0],...
    'string','',...
    'style','text',...
    'tag','txtBarSep2',...
    'units','normalized',... % Be sure to set units before position
    'position',[0 0.95 1 0.001]);

%% Create main subject tabgroup and tabs

% -Please wait- text for when the UI is running
uicontrol(h1338,...
    'style','text',...
    'string','Please Wait',...
    'fontsize',14,...
    'units','normalized',...
    'position',[0 0.75 1 0.1]);

% Tabgroups use normalized units by default (range [0 1])
tabgSubj = uitabgroup(h1338,...
    'position',[0 0.70 1 0.25],...
    'tag','tabgSubj');

% Remove tab
tabRem = uitab(tabgSubj,...
    'backgroundcolor',[0.95 0.95 1],...
    'buttondownfcn',{@gBMP_subjtabrem,h1338},...
    'foregroundcolor',[0.5 0 0],...
    'title','-',...
    'tag','-');

% Add tabs
tabAdd = uitab(tabgSubj,...
    'backgroundcolor',[0.95 0.95 1],...
    'buttondownfcn',{@gBMP_subjtabadd,h1338},...
    'foregroundcolor',[0 0.5 0],...
    'title','+',...
    'tag','+');

% Primary subject tab
tabSubj1 = uitab(tabgSubj,...
    'backgroundcolor',[0.95 0.95 1],...
    'foregroundcolor',[0 0 0],...
    'title','Subj1',...
    'tag','tabSubj1');

set(tabgSubj,'selectedtab',tabSubj1);    

%% Add information fields to subject tab

% == Text uicontrols ==
uicontrol(tabSubj1,...
    'backgroundcolor',[0.95 0.95 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'fontweight','bold',...
    'horizontalalignment','left',...
    'string','Rootfolder',...
    'style','text',...
    'tag','txtRoot1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.01 0.85 0.1 0.1]);

uicontrol(tabSubj1,...
    'backgroundcolor',[0.95 0.95 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'fontweight','bold',...
    'horizontalalignment','left',...
    'string','Trials',...
    'style','text',...
    'tag','txtTrials1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.51 0.85 0.1 0.1]);

uicontrol(tabSubj1,...
    'backgroundcolor',[0.95 0.95 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'fontweight','bold',...
    'horizontalalignment','left',...
    'string','Other',...
    'style','text',...
    'tag','txtOther1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.01 0.7 0.1 0.1]);

uicontrol(tabSubj1,...
    'backgroundcolor',[0.95 0.95 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'fontweight','bold',...
    'horizontalalignment','left',...
    'string','Ignore',...
    'style','text',...
    'tag','txtIgnore1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.01 0.05 0.1 0.1]);

uicontrol(tabSubj1,...
    'backgroundcolor',[0.95 0.95 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'fontweight','bold',...
    'horizontalalignment','left',...
    'string','Exclusive',...
    'style','text',...
    'tag','txtExclusive1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.21 0.05 0.1 0.1]);


% == Edit fields ==

uicontrol(tabSubj1,...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'horizontalalignment','left',...
    'string','',...
    'style','edit',...
    'tag','edtRoot1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.11 0.85 0.34 0.1]);

uicontrol(tabSubj1,...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'horizontalalignment','left',...
    'string','',...
    'style','edit',...
    'tag','edtTrials1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.61 0.85 0.34 0.1]);

uicontrol(tabSubj1,...
    'backgroundcolor',[1 1 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'horizontalalignment','left',...
    'max',2,... % Allows any number of input lines
    'min',0,...
    'string','',...
    'style','edit',...
    'tag','edtOther1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.11 0.2 0.84 0.6]);


% == Pushbuttons ==

uicontrol(tabSubj1,...
    'backgroundcolor',[0.9 0.9 0.9],...
    'callback',{@gBMP_getfile,h1338,'edtRoot1'},...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'horizontalalignment','left',...
    'string','...',...
    'style','pushbutton',...
    'tag','pshRoot1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.45 0.85 0.025 0.1]);


% == Checkboxes ==

uicontrol(tabSubj1,...
    'backgroundcolor',[0.95 0.95 1],...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'horizontalalignment','left',...
    'string','',...
    'style','checkbox',...
    'tag','chkIgnore1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.11 0.05 0.1 0.1]);

uicontrol(tabSubj1,...
    'backgroundcolor',[0.95 0.95 1],...
    'callback',{@gBMP_subjsetexclusive,h1338},...
    'foregroundcolor',[0 0 0],...
    'fontsize',10,...
    'horizontalalignment','left',...
    'string','',...
    'style','checkbox',...
    'tag','chkExclusive1',...
    'units','normalized',... % Be sure to set units before position
    'position',[0.31 0.05 0.34 0.1]);


%% Create modules tabgroups

% Main module tabgroup
tabgMod = uitabgroup(h1338,...
    'position',[0 0.35 1 0.35],...
    'selectionchangedfcn',{@gBMP_modenablexcpt,h1338},...
    'tag','tabgMod',...
    'visible','off');


end