function r = roty(phi)
    % Rotation matrix y
    r = [ ...
        cos(phi)            0           sin(phi);...
        0                   1           0;...
        -sin(phi)           0           cos(phi)];